[package]
name = "malware-accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
reqwest = "0.11"
scraper = "0.13"
serde_json = "1.0"
itertools = "0.10"
crossterm = "0.24"
csv = "1.1"